[project]
name = 'DLC-Stacks'
description = ''
authors = []
telemetry = false
cache_dir = '.cache'

[[project.requirements]]
contract_id = 'STDBEG5X8XD50SPM1JJH0E5CTXGDV5NJTJTTH7YB.redstone-verify'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.sip-010-trait-ft-standard'

[contracts.asset-3]
path = 'external/sbtc/asset-3.clar'
clarity_version = 2
epoch = 2.3

[contracts.clarity-bitcoin-mini-1]
path = 'external/sbtc/clarity-bitcoin-mini-1.clar'
clarity_version = 2
epoch = 2.3

[contracts.dlc-link-callback-trait-v1-1]
path = 'external/dlclink/dlc-link-callback-trait-v1-1.clar'
clarity_version = 2
epoch = 2.3

[contracts.dlc-manager-trait-v1-2]
path = 'external/dlclink/dlc-manager-trait-v1-2.clar'
clarity_version = 2
epoch = 2.3

[contracts.dlc-manager-v1-1]
path = 'external/dlclink/dlc-manager-v1-1.clar'
clarity_version = 2
epoch = 2.3

[contracts.dlc-stablecoin-v1-1]
path = 'external/dlclink/dlc-stablecoin-v1-1.clar'
clarity_version = 2
epoch = 2.3

[contracts.uasu-sbtc-loan-v2]
path = 'contracts/uasu-sbtc-loan-v2.clar'
clarity_version = 2
epoch = 2.3
[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = true
callee_filter = true
