export const CONFIG = {
    VITE_SBTC_COORDINATOR_CID: 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.asset',
    VITE_DLC_LIQUIDATION_RATIO: 14000,  // = 140% - the ratio of collateral to laon below which liquidation can happen
    VITE_DLC_LIQUIDATION_FEE: 1000,     // = 10% - the fee taken for liquidating
    VITE_DLC_EMERGENCY_REFUND_TIME: 144,
    VITE_DLC_CALLBACK_CID: 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.callback-contract',
    //VITE_DLC_UASU_LOAN_CONTRACT: 'STNHKEPYEPJ8ET55ZZ0M5A34J0R3N5FM2CMMMAZ6.uasu-sbtc-loan-v2',
    VITE_DLC_UASU_LOAN_CONTRACT: 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.uasu-sbtc-loan-v2',
    VITE_DLC_DEPLOYER: 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM',
    VITE_DLC_MANAGER_CID: 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.dlc-manager-v1',
    VITE_REDSTONE_VERIFY_CID: 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.redstone-verify',
}

